name: Run Unit Test via Pytest  
  
on: [push]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.10"]  
  
    steps:  
      - uses: actions/checkout@v3  
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root  # Assumes you're using Poetry for dependency management
      - name: Run isort
        run: |
          poetry run isort .
      - name: Run black
        run: | 
          poetry run black .
      - name: Run flake8
        run: |
          poetry run flake8
      - name: Run unit tests
        run: | 
          poetry run pytest